# Generated by Django 3.2.5 on 2021-10-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primer_Nombre', models.CharField(max_length=264)),
                ('Segundo_Nombre', models.CharField(max_length=264)),
                ('Primer_Apellido', models.CharField(max_length=264)),
                ('Segundo_Apellido', models.CharField(max_length=264)),
                ('Tipo_Documento', models.CharField(choices=[('DUI', 'Dui'), ('NIT', 'Nit'), ('PASAPORTE', 'Pasaporte')], max_length=264, unique=True)),
                ('Documento', models.CharField(max_length=264, unique=True)),
                ('Area', models.CharField(choices=[('Finanzas', (('Contador', 'Contador'), ('Tesorero', 'Tesorero'), ('Activo Fijo', 'Activo Fijo'))), ('Legal', (('Gerente Legal', 'Gerente Legal'), ('Oficialia Cumplimiento', 'Oficialia Cumplimiento'))), ('Administrativa', (('Gerente administrativo', 'Gerente administrativo'), ('Unidad de adquisiciones', 'Unidad de aquisiciones')))], max_length=264)),
            ],
        ),
    ]
