# Generated by Django 3.2.5 on 2021-10-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeRecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Tipo_Documento',
            field=models.CharField(choices=[('DUI', 'Dui'), ('NIT', 'Nit'), ('PASAPORTE', 'Pasaporte')], max_length=264),
        ),
    ]
