# Generated by Django 3.2.5 on 2021-10-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeRecord', '0002_alter_empleado_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Primer_Apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Primer_Nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Segundo_Apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Segundo_Nombre',
            field=models.CharField(max_length=30),
        ),
    ]
