# Generated by Django 3.2.5 on 2021-10-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeRecord', '0003_auto_20211013_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Area',
            field=models.CharField(choices=[('Finanzas', (('Contador', 'Contador'), ('Tesorero', 'Tesorero'), ('Activo Fijo', 'Activo Fijo'))), ('Legal', (('Gerente Legal', 'Gerente Legal'), ('Oficialia Cumplimiento', 'Oficialia Cumplimiento'))), ('Administrativa', (('Gerente administrativo', 'Gerente administrativo'), ('Unidad de adquisiciones', 'Unidad de aquisiciones')))], max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Documento',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Tipo_Documento',
            field=models.CharField(choices=[('DUI', 'Dui'), ('NIT', 'Nit'), ('PASAPORTE', 'Pasaporte')], max_length=10),
        ),
    ]
