# Generated by Django 3.2.5 on 2021-10-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeRecord', '0004_auto_20211013_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Documento',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Tipo_Documento',
            field=models.CharField(choices=[('DUI', 'Dui'), ('NIT', 'Nit')], max_length=10),
        ),
    ]
