# Generated by Django 3.2.5 on 2021-10-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeRecord', '0006_alter_empleado_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Documento',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
